# Для начала указываем исходный образ, он будет использован как основа
FROM nginx:latest

#COPY ./ssl.conf .

#RUN openssl req \
#    -x509 \
#    -nodes \
#   -days 1024 \
#    -newkey rsa:2048 \
#    -keyout localhost.key \
#    -out localhost.crt \
#    -config ssl.conf \
#    -extensions 'v3_req'

#RUN cp localhost.crt /etc/ssl/certs/localhost.crt
#RUN cp localhost.key /etc/ssl/private/localhost.key

#COPY nginxtest.loc.pem /etc/ssl/certs/
#COPY nginxtest.loc-key.pem /etc/ssl/private/

#COPY localhost.crt /etc/ssl/certs/
#COPY localhost.key /etc/ssl/private/